stages:
  - name: after_success
    if: branch = master

language: python

services:
  - elasticsearch

python:
  - "3.6"
  - "3.7"

before_install:
  - echo "$RECOGNAI_PYPI_IP $RECOGNAI_PYPI_HOSTNAME" | sudo tee -a /etc/hosts
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U six

script:
  - make dev dist

after_success:
  - pip install twine
  - twine upload dist/*

env:
  - ES_DOC=doc

