language: python

services:
  - elasticsearch

python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -U pip
  - pip install -U six

script:
  - make dev install

after_success:
  - pip install twine
  - twine upload dist/*

env:
  - ES_DOC=doc

